### ISSUE TITLE
What is spite drive and what is tractor beam?

### ISSUE THREAD

**Issue by AndrewSav** [larsiusprime/boardgames#2]
The FAQ section mentions "spite drive" and "tractor beam" - buy those do not seem to be found anywhere in the rules. What are these?

**Comment by larsiusprime** [comment]
Ah, those are things we eventually removed. NHM is *ancient* and I just grabbed the rules off of some old hard drive.

"Spite drive" I think was an "engine" where if/when you died, you did 2 points of damage to every surrounding square around you. It cost one point I believe.

"Tractor beam" I can't even remember. If I had to guess it would be a long-range weapon costing 1 point, that if it makes contact with an enemy, will do 0 damage but cause them to move towards you by one square.

**Comment by AndrewSav** [comment]
@larsiusprime thank you ;)
